version: '3.7'

services:
    app:
        image: jboss/wildfly:latest
        command: sh -c '/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0'
        ports:
            - 8080:8080
            - 9990:9990