version: '3.7'
services:
  mariadb:
    image: mariadb:10.4.17
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=password
    volumes:
     - ./volumes:/var/lib/mysql
    ports:
     - '3306:3306'